GET http://localhost:7070/api/public/getThreads?count=0&size=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiO
###
GET http://localhost:7070/api/public/getAllThreads
###
GET http://localhost:7070/api/public/getThreadById/1
###
GET http://localhost:7070/api/public/sortThreadByCategory/General%20Discussion
###