POST http://localhost:7070/api/security/auth/register

{
    "username": "PatrickUser3",
    "password": "1234",
    "email": "test@email.com"
}
###

POST http://localhost:7070/api/security/auth/login

{
    "username": "PatrickUser3",
    "password": "1234"
}

###
GET http://localhost:7070/api/public/getThreads?count=0&size=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiO
###
GET http://localhost:7070/api/public/getAllThreads
###
GET http://localhost:7070/api/public/getThreadById/13
###
GET http://localhost:7070/api/public/sortThreadByCategory/General%20Discussion
###
POST http://localhost:7070/api/protected/createpost
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJQYXRyaWNrIiwic3ViIjoiUGF0cmlja1VzZXIyIiwiZXhwIjoxNzE2Mzc0MTgyLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6IlBhdHJpY2tVc2VyMiJ9.sy6WtGVxF7dHn7N89mGKau-o3OFGw3Z2GN1BEImqUY8

{
    "content": "This is an example post content.",
    "userName": "PatrickUser2",
    "threadId": 1,
    "replyId": null,
    "parentReplyId": null
}
###
POST http://localhost:7070/api/protected/createthread
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJQYXRyaWNrIiwic3ViIjoiUGF0cmlja1VzZXIyIiwiZXhwIjoxNzE2Mzc0MTgyLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6IlBhdHJpY2tVc2VyMiJ9.sy6WtGVxF7dHn7N89mGKau-o3OFGw3Z2GN1BEImqUY8

{
    "title": "Example Thread Title",
    "content": "This is an example content for the thread.",
    "category": 1,
    "userName": "PatrickUser2"
}
###